apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: custompodautoscalers.custompodautoscaler.com
spec:
  group: custompodautoscaler.com
  names:
    kind: CustomPodAutoscaler
    listKind: CustomPodAutoscalerList
    plural: custompodautoscalers
    shortNames:
    - cpa
    singular: custompodautoscaler
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CustomPodAutoscaler is the Schema for the custompodautoscalers
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CustomPodAutoscalerSpec defines the desired state of CustomPodAutoscaler
          properties:
            config:
              description: Configuration options to be delivered as environment variables
                to the container
              items:
                description: CustomPodAutoscalerConfig defines the configuration options
                  that can be passed to the CustomPodAutoscaler
                properties:
                  name:
                    type: string
                  value:
                    type: string
                required:
                - name
                - value
                type: object
              type: array
            image:
              description: The image of the Custom Pod Autoscaler
              type: string
            pullPolicy:
              description: Pull policy for the Custom Pod Autoscaler, default IfNotPresent
              type: string
            scaleTargetRef:
              description: ScaleTargetRef defining what the Custom Pod Autoscaler
                should manage
              properties:
                apiVersion:
                  description: API version of the referent
                  type: string
                kind:
                  description: 'Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"'
                  type: string
                name:
                  description: 'Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names'
                  type: string
              required:
              - kind
              - name
              type: object
          required:
          - image
          - scaleTargetRef
          type: object
        status:
          description: CustomPodAutoscalerStatus defines the observed state of CustomPodAutoscaler
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
