name: main
on: 
  push:
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get build dependencies
      run: |
        # operator-sdk
        RELEASE_VERSION=v0.10.0
        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /bin/operator-sdk 
        rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Lint 
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        GO111MODULE=off go get -u golang.org/x/lint/golint
        make lint

    - name: Build
      run: |
        if [ ${{ github.event_name }} == "release" ]; then
          VERSION=${{ github.ref }}
        else
          VERSION=$(git rev-parse --short ${{ github.sha }})
        fi
        make VERSION=${VERSION}

    - name: Deploy
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      if: github.event_name != 'pull_request' && github.repository == 'jthomperoo/custom-pod-autoscaler-operator'
      run: |
        docker login --username=$DOCKER_USER --password=$DOCKER_PASS
        if [ ${{ github.event_name }} == "release" ]; then
          docker tag custompodautoscaler/operator:${{ github.ref }} custompodautoscaler/operator:latest
          docker push custompodautoscaler/operator:${{ github.ref }}
          docker push custompodautoscaler/operator:latest
        else
          docker push custompodautoscaler/operator:$(git rev-parse --short ${{ github.sha }})
        fi
