name: main
on: 
  push:
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get build dependencies
      run: |
        # operator-sdk
        RELEASE_VERSION=v0.12.0
        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /bin/operator-sdk 
        rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Lint, unit test and build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        GO111MODULE=off go get -u golang.org/x/lint/golint

        make lint

        # Run code generation
        make generate
        # Check diff for changes in committed code and generated code
        git diff --exit-code
        
        make unittest

        if [ ${{ github.event_name }} == "release" ]; then
          # github.ref is in the form refs/tags/VERSION, so apply regex to just get version
          VERSION=$(echo "${{ github.ref }}" | grep -P '([^\/]+$)' -o) 
        else
          VERSION=$(git rev-parse --short ${{ github.sha }})
        fi

        make VERSION=${VERSION}

    - uses: codecov/codecov-action@v1.0.3
      if: github.repository == 'jthomperoo/custom-pod-autoscaler-operator'
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./unit_cover.out
        flags: unittests
        name: custom-pod-autoscaler-operator-unittests

    - name: Deploy
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      if: github.event_name != 'pull_request' && github.repository == 'jthomperoo/custom-pod-autoscaler-operator'
      run: |
        if [ ${{ github.event_name }} == "release" ]; then
          # github.ref is in the form refs/tags/VERSION, so apply regex to just get version
          VERSION=$(echo "${{ github.ref }}" | grep -P '([^\/]+$)' -o) 
        else
          VERSION=$(git rev-parse --short ${{ github.sha }})
        fi
        echo "$DOCKER_PASS" | docker login --username=$DOCKER_USER --password-stdin
        docker push custompodautoscaler/operator:${VERSION}
        if [ ${{ github.event_name }} == "release" ]; then
          docker tag custompodautoscaler/operator:${VERSION} custompodautoscaler/operator:latest
          docker push custompodautoscaler/operator:latest
        fi

    - name: Bundle YAML config
      if: github.event_name == 'release' && github.repository == 'jthomperoo/custom-pod-autoscaler-operator'
      run: |
        mkdir dist dist/cluster dist/namespace

        # Copy cluster/namespace scope config
        cp -r deploy/cluster/* deploy/crds/* dist/cluster
        cp -r deploy/namespace/* deploy/crds/* dist/namespace

        # Variables to sub into k8s templates
        if [ ${{ github.event_name }} == "release" ]; then
          # github.ref is in the form refs/tags/VERSION, so apply regex to just get version
          VERSION=$(echo "${{ github.ref }}" | grep -P '([^\/]+$)' -o) 
        else
          VERSION=$(git rev-parse --short ${{ github.sha }})
        fi
        export VERSION=${VERSION}

        # Substitute in variaibles
        for f in $(find dist/ -name \*.yaml -print); do
          envsubst < ${f} > ${f}.tmp && mv ${f}.tmp ${f}
        done

        tar -czvf cluster.tar.gz dist/cluster/*
        tar -czvf namespace.tar.gz dist/namespace/*

    - name: Deploy cluster-scope YAML config
      if: github.event_name == 'release' && github.repository == 'jthomperoo/custom-pod-autoscaler-operator'
      uses: Shopify/upload-to-release@1.0.0
      with:
        name: cluster.tar.gz
        path: cluster.tar.gz
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy namespace-scope YAML config
      if: github.event_name == 'release' && github.repository == 'jthomperoo/custom-pod-autoscaler-operator'
      uses: Shopify/upload-to-release@1.0.0
      with:
        name: namespace.tar.gz
        path: namespace.tar.gz
        repo-token: ${{ secrets.GITHUB_TOKEN }}