name: main
on: 
  push:
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get build dependencies
      run: |
        # operator-sdk
        RELEASE_VERSION=v0.10.0
        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /bin/operator-sdk 
        rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Lint 
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        GO111MODULE=off go get -u golang.org/x/lint/golint
        make lint

    - name: Build
      run: |
        if [ ${{ github.event_name }} == "release" ]; then
          # github.ref is in the form refs/tags/VERSION, so apply regex to just get version
          VERSION=$(echo "${{ github.ref }}" | grep -P '([^\/]+$)' -o) 
        else
          VERSION=$(git rev-parse --short ${{ github.sha }})
        fi
        make VERSION=${VERSION}

    - name: Deploy
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      if: github.event_name != 'pull_request' && github.repository == 'jthomperoo/custom-pod-autoscaler-operator'
      run: |
        echo "$DOCKER_PASS" | docker login --username=$DOCKER_USER --password-stdin
        if [ ${{ github.event_name }} == "release" ]; then
          # This needs to be determined again, due to env vars not being shared between steps
          # https://github.com/actions/starter-workflows/issues/68
          VERSION=$(echo "${{ github.ref }}" | grep -P '([^\/]+$)' -o) 
          docker tag custompodautoscaler/operator:${VERSION} custompodautoscaler/operator:latest
          docker push custompodautoscaler/operator:${VERSION}
          docker push custompodautoscaler/operator:latest
        else
          docker push custompodautoscaler/operator:$(git rev-parse --short ${{ github.sha }})
        fi

    - name: Bundle YAML config
      if: github.event_name == 'release' && github.repository == 'jthomperoo/custom-pod-autoscaler-operator'
      run: |
        export VERSION="$(echo "${{ github.ref }}" | grep -P '([^\/]+$)' -o) "
        mkdir dist
        cp -r deploy/* dist/
        envsubst < deploy/operator.yaml > dist/operator.yaml
        tar -czvf deploy.tar.gz dist/*

    - name: Deploy YAML config
      if: github.event_name == 'release' && github.repository == 'jthomperoo/custom-pod-autoscaler-operator'
      uses: Shopify/upload-to-release@1.0.0
      with:
        name: deploy.tar.gz
        path: deploy.tar.gz
        repo-token: ${{ secrets.GITHUB_TOKEN }}
